# Generated by Django 2.2.2 on 2019-06-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_tweet_isreply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='isReply',
            new_name='is_reply',
        ),
    ]
